# This is a basic workflow to help you get started with Actions

name: Configuration Variable workflow

# Controls when the workflow will run
on:
 workflow_dispatch
env:
  cloud: AWS
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greeting-job of configuration variable"
  Greeting-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      Greeting: Hello
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     # Runs a single command using the runners shell
      - name: Run a workflow on configuration variable
        run: echo "$Greeting $FirstName is using $cloud with projet ${{var.project_id}}"
        env:
          FirstName: Parul

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
