# This is a workflow to help retrieve secret value in Actions

name: Testing Secret Variable

on:
  workflow_dispatch
env:
  ACTION_STEPS_DEBUG: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_secret_variable:
    runs-on: ubuntu-latest
    steps:
      - name: "retrieve secret variable"
        run: | 
          echo "Repository name : ${{github.repository}}"
          echo "workflow name : ${{github.workflow}}"
          echo "Triggered by : ${{github.triggering_actor}}"
          echo "Secret Value : ${{ secrets.project_secret_key }}"
