# This is a workflow for demonstrating user input variables in Github Actions

name: User Input Variable

on:
  workflow_dispatch:
    inputs:
      number1:
        description: "First Number"
        default: '0'
        required: true
      number2:
        description: "Second Number"
        default: '0'
        required: true
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add_two_numbers:
    runs-on: ubuntu-latest
    steps:
      - name: Adding two numbers
        id: sum
        run: echo "$((${{ inputs.number1 }} + ${{ inputs.number2 }}))" >> ${{ vars.sum }}
      - name: Display Sum
        run: echo "The sum of ${{ inputs.number1 }} and ${{ inputs.number2 }} is $sum"
