# This is a workflow for demonstrating variables in Github Actions

name: Testing workflow variable

# Controls when the workflow will run
on:
  workflow_dispatch
env:
  cloud: AWS

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Say Hello, Its variable workflow"
        run: echo "$Greeting $FirstName is using $cloud"
        env: 
          FirstName: Parul
